json.id port.id
json.address port.address
json.city port.city
json.country port.country
json.latitude port.latitude
json.longitude port.longitude
json.image_url port.image_url
json.currency port.currency
json.created_at port.created_at
json.updated_at port.updated_at